export default {
    adType: 'ADTYPE',
    vehicleType: 'VEHICLETYPE',
    'vehicleFunctionUse.value': 'FN_USE',
    'vehicleTypeSelect.value': 'TYPE',
    'manufacturer.make.value': 'MAKE',
    'vehicleEngine.type.value': 'ENGINE_TYPE',
    'vehicleEngine.gas.value': 'ENGINE_GAS',
    'vehicleEngine.cylinder': 'CYLINDER',
    'vehicleGeneralState.value': 'GENERAL_STATE',
    'address.city.postcode': 'ADDRESS_CITY_POSTCODE',
    'price': 'AD_PRICE',
    'mileage': 'MILEAGE',
    'power.kw': 'POWER_KW',
    'consumption.gkm': 'CONSUMPTION_GKM',
    'doors': 'DOORS',
    'seats': 'SEATS',
    'bunks': 'BUNKS',
    'driverCabin': 'DRIVER_CAB',
    'hoursOfUse': 'HOURS_USE',
    'equipments': {
        name: 'EQUIPMENTS',
        type: 'array',
        selector: 'value',
    },
    'bedType.value': 'BED_TYPE',
    'materials.value': 'MATERIALS',
    'emission.value': 'EMISSION',
    'paint.value': 'PAINT',
    'externalColor.value': 'EXTERNAL_COLOR',
    'internalColor.value': 'INTERNAL_COLOR',
};
